# U-Net-FNO Configuration for Peak Preservation and Multi-scale Training

# Data parameters
data:
  data_dir: ../GAN/data_wss_dirty
  validation_dir: ../GAN/validation_wss_dirty
  max_train: 11050
  max_val: 2781
  batch_size: 24  # Slightly reduced for larger model
  num_workers: 4
  pin_memory: true
  shape: [64, 64]

# Model parameters with attention and increased capacity
model:
  in_channels: 2
  out_channels: 2
  base_channels: 96           # Increased from 64
  depth: 3
  modes: 16                   # Increased from 12
  enforce_incompressible: true
  use_attention: true         # Attention gates in decoder
  
# Training parameters with multi-scale loss
training:
  epochs: 150
  learning_rate: 0.0002
  weight_decay: 0.000005      # Reduced weight decay
  use_mixed_precision: false
  gradient_clipping: 0.3      # Reduced from 0.5
  noise_std: 0.02             # Training noise for robustness
  
  # Physics weights with peak preservation losses
  physics_weights:
    mse: 0.7                  # Base reconstruction
    weighted_mse: 0.3         # Emphasize high-velocity regions
    huber: 0.2                # Peak preservation
    magnitude_l1: 0.1         # Velocity magnitude preservation
    divergence: 0.05          # Physics constraint
    boundary: 0.001           # Boundary conditions
    frequency: 0.05           # Frequency domain consistency
  
  # Learning rate scheduling with warm restarts
  scheduler_type: "CosineAnnealingWarmRestarts"
  T_0: 25                     # Initial restart period
  T_mult: 2                   # Period multiplier
  eta_min: 0.000001          # Minimum learning rate
  
  # Validation and saving
  validation_interval: 5
  save_interval: 15
  visualization_interval: 5

# Output parameters
output:
  output_dir: ./results_unet_fno_attention
  save_best_model: true
  save_visualizations: true
  
# Hardware optimization
hardware:
  use_gpu: true
  num_workers: 4
  pin_memory: true

# Reproducibility
reproducibility:
  seed: 42
  deterministic: true

# Monitoring with peak analysis
monitoring:
  tensorboard: true
  log_level: "INFO"
  track_metrics:
    - "train_loss"
    - "val_loss"
    - "mse_loss"
    - "weighted_mse_loss"
    - "huber_loss"
    - "magnitude_l1_loss"
    - "divergence_loss"
    - "boundary_loss"
    - "frequency_loss"
    - "learning_rate"
    - "peak_analysis"
    - "high_velocity_metrics"